"""empty message

Revision ID: 0112429a60f7
Revises: 
Create Date: 2023-07-19 14:58:27.234712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0112429a60f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karuta_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_line1', sa.String(length=1000), nullable=True),
    sa.Column('english_line2', sa.String(length=1000), nullable=True),
    sa.Column('english_line3', sa.String(length=1000), nullable=True),
    sa.Column('english_line4', sa.String(length=1000), nullable=True),
    sa.Column('english_line5', sa.String(length=1000), nullable=True),
    sa.Column('english_author', sa.String(length=1000), nullable=True),
    sa.Column('japanese_line1', sa.String(length=1000), nullable=True),
    sa.Column('japanese_line2', sa.String(length=1000), nullable=True),
    sa.Column('japanese_line3', sa.String(length=1000), nullable=True),
    sa.Column('japanese_line4', sa.String(length=1000), nullable=True),
    sa.Column('japanese_line5', sa.String(length=1000), nullable=True),
    sa.Column('japanese_author', sa.String(length=1000), nullable=True),
    sa.Column('romaji_line1', sa.String(length=1000), nullable=True),
    sa.Column('romaji_line2', sa.String(length=1000), nullable=True),
    sa.Column('romaji_line3', sa.String(length=1000), nullable=True),
    sa.Column('romaji_line4', sa.String(length=1000), nullable=True),
    sa.Column('romaji_line5', sa.String(length=1000), nullable=True),
    sa.Column('romaji_author', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('deck_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('answer_long', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck_card_association',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('deck_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_card_id'], ['deck_cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'deck_card_id')
    )
    op.create_table('user_deck_association',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_deck_association')
    op.drop_table('deck_card_association')
    op.drop_table('decks')
    op.drop_table('deck_cards')
    op.drop_table('users')
    op.drop_table('karuta_cards')
    # ### end Alembic commands ###
