"""empty message

Revision ID: 47798ef13180
Revises: 
Create Date: 2023-07-07 10:17:51.218133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47798ef13180'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karuta_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_line1', sa.String(length=1000), nullable=True),
    sa.Column('english_line2', sa.String(length=1000), nullable=True),
    sa.Column('english_line3', sa.String(length=1000), nullable=True),
    sa.Column('english_line4', sa.String(length=1000), nullable=True),
    sa.Column('english_line5', sa.String(length=1000), nullable=True),
    sa.Column('english_author', sa.String(length=1000), nullable=True),
    sa.Column('japanese_line1', sa.String(length=1000), nullable=True),
    sa.Column('japanese_line2', sa.String(length=1000), nullable=True),
    sa.Column('japanese_line3', sa.String(length=1000), nullable=True),
    sa.Column('japanese_line4', sa.String(length=1000), nullable=True),
    sa.Column('japanese_line5', sa.String(length=1000), nullable=True),
    sa.Column('japanese_author', sa.String(length=1000), nullable=True),
    sa.Column('romaji_line1', sa.String(length=1000), nullable=True),
    sa.Column('romaji_line2', sa.String(length=1000), nullable=True),
    sa.Column('romaji_line3', sa.String(length=1000), nullable=True),
    sa.Column('romaji_line4', sa.String(length=1000), nullable=True),
    sa.Column('romaji_line5', sa.String(length=1000), nullable=True),
    sa.Column('romaji_author', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('karuta_cards')
    # ### end Alembic commands ###
